export * from "./harmonitzats";
export * from "./ordenances-list";
export * from "./cities";
export * from "./codificats";
export * from "./v_tables";
export * from "./miscelanea";
export * from "./velocitats";
export * from "./alcoholemies";
export * from "./drogues";
export * from "./horaris-epar";
export * from "./armes";
export * from "./d_lleus";
export * from "./d_vido";
export * from "./d_imp_acc";
export * from "./inmovilitzacions"
export * from "./cata_permis"
